version: '3.8'

services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: YourStrongPass@2023!
      ACCEPT_EULA: Y
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
    driver: local
