version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet_api
    ports:
      - "8080:8080"
      - "8081:8081"
      - "443:443"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080;https://0.0.0.0:443"
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=TuBaseDeDatos;User Id=sa;Password=YourStrongPass@2023!;"
    depends_on:
      - sqlserver
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
